name: ex3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  dio: ^5.4.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  http: ^1.1.2
  provider: ^6.1.1
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
